### ISSUE TITLE
kernel dependencies not always built 

### ISSUE THREAD

**Issue by hmbedded** [celaxodon/buildroot#5]
Using the nano-package-series branch (haven't tried the others) I found that sometimes the recipes to pull in the nvidia drivers and device tree were not always triggered. Building from scratch is OK, so 'make clean all' succeeds. However, for instance, 'make clean linux' fails.

I've fixed this issue in my fork. Have a look at this branch: [https://github.com/hmbedded/buildroot/commits/nano-package-series-hmbedded-mods](url) where I built upon nano-package-series. Also this branch: [https://github.com/hmbedded/buildroot/commits/l4t-32.5-jetson-nano](url) where I've consolidated the commits and also upgraded to LT4 32.5.

**Comment by celaxodon** [comment]
Currently working on incorporating your changes for the 32.5 release and the kernel dependencies. Excellent work @hmbedded, thank you for opening the issue and working on this!

**Comment by celaxodon** [comment]
Closing this issue out after pull request #10
